### ISSUE TITLE
Channel closed - after restart flows

### ISSUE THREAD

**Issue by jaroslaw81** [Stormpass/node-red-contrib-amqp#9]
After creating a flow with manual message acknowledgment, Node-RED automatically restarts with the following message. I also copied the example, and the same error occurs. The Node-RED version is 3.1.8.

[error] IllegalOperationError: Channel closed
    at Channel.<anonymous> (/usr/src/node-red/node_modules/amqplib/lib/channel.js:159:11)
    at C.closeBecause (/usr/src/node-red/node_modules/amqplib/lib/channel.js:211:8)
    at /usr/src/node-red/node_modules/amqplib/lib/channel_model.js:72:19
    at node:internal/util:441:7
    at new Promise (<anonymous>)
    at node:internal/util:427:12
    at Channel.close (/usr/src/node-red/node_modules/amqplib/lib/channel_model.js:74:7)
    at reconnect (/usr/src/node-red/node_modules/@stormpass/node-red-contrib-amqp/build/src/nodes/amqp-out.js:74:29)
    at Channel.<anonymous> (/usr/src/node-red/node_modules/@stormpass/node-red-contrib-amqp/build/src/nodes/amqp-out.js:110:31)

**Comment by roblen45** [comment]
Same here

**Comment by zba** [comment]
seems it related to #5 , the crash breaks deploy making node impossible to reconfigure, I had to make rabbitmq unavalable (and also got crash when it was stopped)  just to deploy, any way to workaround  ?

**Comment by zazin** [comment]
I also experienced the same issue, which is an error when restarting the application.

please follow this link if you need the best solution.

[https://github.com/Stormpass/node-red-contrib-amqp/issues/5#issuecomment-2150479020](https://github.com/Stormpass/node-red-contrib-amqp/issues/5#issuecomment-2150479020)
